feat: allow provided config object to extend other configs

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,23 +1,9 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
-
-message="$(cat $1)"
-requiredPattern="^(web|mobile|common)/^(feat|add|cut|fix|bump|make|start|stop|refactor|reformat|optimise|document|merge) : .*$"
-if ! [[ $message =~ $requiredPattern ]];
-then
-  echo "-"
-  echo "-"
-  echo "-"
-  echo "🚨 Wrong commit message! 😕"
-  echo "The commit message must have this format:"
-  echo "<verb in imperative mood> <what was done>"
-  echo "Allowed verbs in imperative mood: add, cut, fix, bump, make, start, stop, refactor, reformat, optimise, document, merge"
-  echo "Example: add login button"
-  echo "-"
-  echo "Your commit message was:"
-  echo $message
-  echo "-"
-  echo "For more information, check script in .husky/commit-msg"
-  echo "-"
-  exit 1
+#!/bin/sh
+if ! head -1 "$1" | grep -qE "^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\(.+?\))?: .{1,}$"; then
+    echo "Aborting commit. Your commit message is invalid." >&2
+    exit 1
+fi
+if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
+    echo "Aborting commit. Your commit message is too long." >&2
+    exit 1
 fi
